routes/web.php
<?php
Route::get('portal/cadastro/{id}', 'PortalCadastroController@cadastro')->name('portal.cadastro');
Route::resource('portal', 'PortalCadastroController');

Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

// Registration Routes..
$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
$this->post('register', 'Auth\RegisterController@register')->name('auth.register');

$this->get('invitation/{invitation_token}', 'Auth\RegisterController@processInvitation')->name('auth.invitation');

Route::group(['middleware' => ['auth', 'check_invitation'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('properties', 'Admin\PropertiesController');
    Route::post('properties_mass_destroy', ['uses' => 'Admin\PropertiesController@massDestroy', 'as' => 'properties.mass_destroy']);
    Route::post('properties_restore/{id}', ['uses' => 'Admin\PropertiesController@restore', 'as' => 'properties.restore']);
    Route::delete('properties_perma_del/{id}', ['uses' => 'Admin\PropertiesController@perma_del', 'as' => 'properties.perma_del']);
    Route::resource('documents', 'Admin\DocumentsController');
    Route::post('documents_mass_destroy', ['uses' => 'Admin\DocumentsController@massDestroy', 'as' => 'documents.mass_destroy']);
    Route::post('documents_restore/{id}', ['uses' => 'Admin\DocumentsController@restore', 'as' => 'documents.restore']);
    Route::delete('documents_perma_del/{id}', ['uses' => 'Admin\DocumentsController@perma_del', 'as' => 'documents.perma_del']);
    Route::resource('notes', 'Admin\NotesController');
    Route::post('notes_mass_destroy', ['uses' => 'Admin\NotesController@massDestroy', 'as' => 'notes.mass_destroy']);
    Route::post('notes_restore/{id}', ['uses' => 'Admin\NotesController@restore', 'as' => 'notes.restore']);
    Route::delete('notes_perma_del/{id}', ['uses' => 'Admin\NotesController@perma_del', 'as' => 'notes.perma_del']);

    Route::model('messenger', 'App\MessengerTopic');
    Route::get('messenger/inbox', 'Admin\MessengerController@inbox')->name('messenger.inbox');
    Route::get('messenger/outbox', 'Admin\MessengerController@outbox')->name('messenger.outbox');
    Route::resource('messenger', 'Admin\MessengerController');

    Route::resource('tenants', 'Admin\TenantsController');

    Route::resource('pessoa', 'Admin\PessoaController');

    Route::get('membro', 'Admin\MembroController@index')->name('membro.index');
    Route::get('membro/rede', 'Admin\MembroController@rede')->name('membro.rede');

    
    Route::get('produto/kit', 'Admin\ProdutoController@kit')->name('produto.kit');
    Route::get('produto/selecionar/{id}', 'Admin\ProdutoController@selecionar')->name('produto.selecionar');

    Route::resource('produto', 'Admin\ProdutoController');
});

app/Http/Controllers/Admin/ProdutoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Document;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreDocumentsRequest;
use App\Http\Requests\Admin\UpdateDocumentsRequest;
use App\Http\Controllers\Traits\FileUploadTrait;
use App\Database\Repositories;
use Illuminate\Support\Facades\Input;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Requests\Admin\StoreUsersRequest;
use Illuminate\Support\Facades\Auth;

class ProdutoController extends Controller
{

    /**
     * Display a listing of Document.
     *
     * @return \Illuminate\Http\Response
     */

    private $repository;
    private $bancoRepository;
    private $tipoStatusRepository;
    private $pessoaRepository;

    public function __construct(Repositories\PessoaRepository $pessoaRepository,Repositories\ProdutoRepository $repository, Repositories\BancoRepository $bancoRepository, Repositories\TipoStatusRepository $tipoStatusRepository)
    {
        $this->repository = $repository;
        $this->bancoRepository = $bancoRepository;
        $this->tipoStatusRepository = $tipoStatusRepository;
        $this->pessoaRepository = $pessoaRepository;
    }

    public function index()
    {
        $objetos = $this->repository->findAll();
        return view('admin.produto.index', compact('objetos'));
    }

    public function create()
    {
        return view('admin.produto.create', compact(''));
    }

    public function store(Request $request)
    {
        try {
            $objeto = $this->repository->create($request);
            return redirect('/admin/produto');

        } catch (Exception $ex) {

        }

    }

    public function edit($id)
    {
        $produto = $this->repository->findId($id);
        return view('admin.produto.edit', compact('produto'));
    }


    public function update(Request $request, $id)
    {
        try {
            $objeto = $this->repository->update($request, $id);
            return redirect()->route('admin.produto.index');
        } catch (Exception $ex) {

        }
    }

    public function kit()
    {   
        $root = $this->pessoaRepository->findIdUser(Auth::user()->id);
        $objetos = $this->repository->findAll();
        return view('admin.produto.kit', compact('objetos','root'));
    }

    public function selecionar($id)
    {
        $root = $this->pessoaRepository->findIdUser(Auth::user()->id);
        $this->repository->selecionarKit($id, $root->id_pessoa);
        return redirect()->route('admin.produto.kit');
    }


    public function destroy($id)
    {
        $this->repository->destroy($id);
        return redirect()->route('admin.produto.index');
    }


}

resources/views/admin/produto/create.blade.php
@extends('layouts.app')

@section('content')
<h3 class="page-title">Cadastro de Produto</h3>
</h3>
{!! Form::open(['method' => 'POST', 'route' => ['admin.produto.store'], 'class'=>'form-horizontal','enctype'=>"multipart/form-data"]) !!}

<div class="panel panel-default">
    <div class="panel-heading">
        @lang('global.app_create')
    </div>
    <div class="panel-body">
        <div class="form-group">
            <label class="col-md-1 control-label" for="nome">Nome</label>
            <div class="col-md-11">
                <input id="nome" name="nome" type="text" placeholder="Nome" class="form-control input-md" required="">
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-1 control-label" for="Nome">Valor </label>
            <div class="col-md-5">
                <input type="text" id="valor" name="valor" class="valor form-control" style="display:inline-block" />
            </div>

            <label class="col-md-1 control-label" for="sexo">Publicado</label>
            <div class="col-md-3">
                <select class="form-control select2me uppercase" id="status" name="status">
                    <option value="">Selecione</option>
                    <option value="1" selected="selected">Ativo</option>
                    <option value="2">Inativo</option>
                </select>
            </div>

        </div>
        <div class="form-group">
            <label class="col-md-1 control-label" for="arquivo">Arquivo</label>
            <div class="col-md-5">
                <input id="arquivo" name="arquivo" type="file" placeholder="arquivo" class="form-control input-md">
            </div>
        </div>
        <div class="form-group">
                <label class="col-md-1 control-label" for="descricao">Descrição</label>
                <div class="col-md-11">
                    <textarea name="descricao" style="width: 100%; height: 70px"></textarea>
                </div>    
            </div>
    </div>
</div>

{!! Form::submit('Salvar', ['class' => 'btn btn-primary']) !!}
<a href="{!! route('admin.pessoa.index') !!}" class="btn btn-danger">Voltar</a>
{!! Form::close() !!}
@stop

@section('javascript')
<script>
    $(document).ready(function () {
        $('.valor').mask('#.##0,00', {reverse: true});
    });
</script>
@endsection

resources/views/admin/produto/edit.blade.php
@extends('layouts.app')

@section('content')
<h3 class="page-title">@lang('global.produto.title')</h3>
{!! Form::model($produto, ['method' => 'PUT', 'route' => ['admin.produto.update', $produto->id_produto],'class'=>'form-horizontal','enctype'=>"multipart/form-data"]) !!}
<div class="panel panel-default">
    <div class="panel-heading">
        @lang('global.app_create')
    </div>
    <div class="panel-body">
        <div class="form-group">
            <label class="col-md-1 control-label" for="nome">Nome</label>
            <div class="col-md-11">
            <input id="nome" value="{{$produto->nome}}" name="nome" type="text" placeholder="Nome" class="form-control input-md" required="">
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-1 control-label" for="Nome">Valor </label>
            <div class="col-md-5">
                <input type="text" value="{{$produto->valor}}" id="valor" name="valor" class="valor form-control" style="display:inline-block" />
            </div>

            <label class="col-md-1 control-label" for="sexo">Publicado</label>
            <div class="col-md-3">
                <select class="form-control select2me uppercase" id="status" name="status">
                    <option value="">Selecione</option>
                    <option value="1" {{$produto->status == '1' ? 'selected="selected"' : ''}}>Ativo</option>
                    <option value="2" {{$produto->status == '2' ? 'selected="selected"' : ''}}>Inativo</option>
                </select>
            </div>

        </div>
        <div class="form-group">
            <label class="col-md-1 control-label" for="arquivo">Arquivo</label>
            <div class="col-md-5">
                <input id="arquivo" name="arquivo" type="file" placeholder="arquivo" class="form-control input-md">
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-1 control-label" for="descricao">Descrição</label>
            <div class="col-md-11">
                <textarea name="descricao" style="width: 100%; height: 70px">{!!$produto->descricao!!}</textarea>
            </div>
        </div>
    </div>
</div>

{!! Form::submit('Salvar', ['class' => 'btn btn-primary']) !!}
<a href="{!! route('admin.produto.index') !!}" class="btn btn-danger">Voltar</a>
{!! Form::close() !!}
@stop

@section('javascript')
<script>
    $(document).ready(function () {
        $('.valor').mask('#.##0,00', {reverse: true});
    });
</script>
@endsection

resources/views/admin/produto/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
<h3 class="page-title">Produtos</h3>
@can('user_create')
<p>
    <a href="{{ route('admin.produto.create') }}" class="btn btn-success">Novo</a>

</p>
@endcan

<div class="panel panel-default">
    <div class="panel-heading">
        @lang('global.app_list')
    </div>

    <div class="panel-body table-responsive">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Imagem</th>
                    <th>Status</th>
                    <th>&nbsp;</th>

                </tr>
            </thead>

            <tbody>
                @if (count($objetos) > 0)
                @foreach ($objetos as $objeto)
                <tr data-entry-id="{{ $objeto->id_produto }}">
                    <td style="width: 80%;">
                        <img id="myImg" src="data:application/image;base64,{{ base64_encode($objeto->getImagem()) }}"
                            class="img-responsive thumbnail" style="width: 100%; max-height: 260px;" />
                    </td>
                    <td>
                        @if($objeto->status == '2')
                        <i class="fa fa-eye-slash fw"></i>
                        @else
                        <i class="fa fa-eye fw"></i>
                        @endif
                    </td>
                    <td>
                        @can('user_edit')
                        <a href="{{ route('admin.produto.edit',[$objeto->id_produto]) }}" class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                        @endcan
                        @can('user_delete')
                        {!! Form::open(array(
                        'style' => 'display: inline-block;',
                        'method' => 'DELETE',
                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                        'route' => ['admin.produto.destroy', $objeto->id_produto])) !!}
                        {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                        {!! Form::close() !!}
                        @endcan
                    </td>

                </tr>
                @endforeach
                @else
                <tr>
                    <td colspan="10">@lang('global.app_no_entries_in_table')</td>
                </tr>
                @endif
            </tbody>
        </table>
    </div>
</div>
@stop

@section('javascript')

@endsection

resources/views/admin/produto/kit.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
<h3 class="page-title">Produtos</h3>
@can('user_create')
<p>
    <a href="{{ route('admin.produto.create') }}" class="btn btn-success">Novo</a>

</p>
@endcan

<div class="panel panel-default">
    <div class="panel-heading">
        @lang('global.app_list')
    </div>

    <div class="panel-body table-responsive">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Produto</th>
                    
                    <th>&nbsp;</th>

                </tr>
            </thead>

            <tbody >
                @if (count($objetos) > 0)
                @foreach ($objetos as $objeto)
                <tr data-entry-id="{{ $objeto->id_produto }}"  style="{{$root->id_produto == $objeto->id_produto ? "background-color: #c0c1c1" : ''}}">
                    <td style="width: 90%;">
                        <img id="myImg" src="data:application/image;base64,{{ base64_encode($objeto->getImagem()) }}" class="img-responsive" style="width: 100%; max-height: 260px;"/>
                    </td>
                    <td style="text-align: center;vertical-align: middle;">
                        <a href="{{ route('admin.produto.selecionar',[$objeto->id_produto]) }}" class="btn btn-xs btn-info">Selecionar</a>
                    </td>

                </tr>
                @endforeach
                @else
                <tr>
                    <td colspan="10">@lang('global.app_no_entries_in_table')</td>
                </tr>
                @endif
            </tbody>
        </table>
    </div>
</div>
@stop

@section('javascript')
<script>
        $(document).ready(function () {
            $('.valor').mask('#.##0,00', {reverse: true});
        });
    </script>
@endsection

resources/views/admin/produto/show.blade.php
@extends('layouts.app')

@section('content')
<h3 class="page-title">@lang('global.pessoa.title')</h3>

<div class="panel panel-default">
    <div class="panel-heading">
        @lang('global.app_view')
    </div>
    <div class="panel-body table-responsive">
        <div class="row">
            <div class="col-md-6">
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>Nome</th>
                        <th>Indicador</th>
                        <th>E-mail</th>
                        <th>CPF</th>
                        <th>Sexo</th>
                        <th>Cidade/UF</th>
                        <th>Status</th>
                        <th>Data Cadastro</th>
                        <th>Acesso</th>
                        <th>Ação</th>
                    </tr>
                    @foreach ($objetos as $objeto)
                    <tr>
                        <td>{{$objeto->nome}}</td>
                        <td>{{$objeto->indicador}}</td>
                        <td>{{$objeto->email}}</td>
                        <td>{{$objeto->cpf}}</td>
                        <td>{{$objeto->sexo}}</td>
                        <td>{{$objeto->cidade}} / {{$objeto->uf}}</td>
                        <td>{{$objeto->tipo_status->descricao}}</td>
                        <td>{{$objeto->getDataCadastro()}}</td>
                        <td>link</td>
                        <td>
                            @can('user_view')
                            <a href="{{ route('admin.users.show',[$objeto->id_pessoa]) }}" class="btn btn-xs btn-primary">@lang('global.app_view')</a>
                            @endcan
                            @can('user_edit')
                            <a href="{{ route('admin.users.edit',[$objeto->id_pessoa]) }}" class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                            @endcan
                            @can('user_delete')
                            {!! Form::open(array(
                                'style' => 'display: inline-block;',
                                'method' => 'DELETE',
                                'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                'route' => ['admin.users.destroy', $objeto->id_pessoa])) !!}
                            {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                            {!! Form::close() !!}
                            @endcan
                        </td>

                    </tr>
                    @endforeach

                </table>
            </div>
        </div><!-- Nav tabs -->


    </div>
</div>
@stop